# Generated by Django 3.2.5 on 2021-08-09 09:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations_app', '0001_initial'),
        ('escape_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='owner_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='organizations_app.company'),
        ),
        migrations.AddField(
            model_name='review',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escape_app.room'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escape_app.room'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escape_app.team'),
        ),
        migrations.AddField(
            model_name='game',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escape_app.room'),
        ),
        migrations.AddField(
            model_name='game',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escape_app.team'),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.CheckConstraint(check=models.Q(('max_players__gte', django.db.models.expressions.F('min_players'))), name='check_room_min_max_players'),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.UniqueConstraint(fields=('room', 'start_datetime'), name='reservation unique room start_datetime'),
        ),
    ]
