# Generated by Django 3.2.5 on 2021-08-01 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escape_rooms_app', '0002_team_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='room',
            field=models.ForeignKey(default=98765, on_delete=django.db.models.deletion.CASCADE, to='escape_rooms_app.room'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='team',
            field=models.ForeignKey(default=87654, on_delete=django.db.models.deletion.CASCADE, to='escape_rooms_app.team'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='title',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
