# Generated by Django 3.2.5 on 2021-08-01 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escape_rooms_app', '0003_auto_20210801_1159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='title',
            new_name='name',
        ),
    ]
