# Generated by Django 3.2.5 on 2021-08-01 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escape_rooms_app', '0004_rename_title_room_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='room',
            field=models.ForeignKey(default=98765, on_delete=django.db.models.deletion.CASCADE, to='escape_rooms_app.room'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='team',
            field=models.ForeignKey(default=87654, on_delete=django.db.models.deletion.CASCADE, to='escape_rooms_app.team'),
            preserve_default=False,
        ),
    ]
