# Generated by Django 3.2.5 on 2021-08-01 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escape_rooms_app', '0005_auto_20210801_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='datetime',
            field=models.DateTimeField(unique=True),
        ),
    ]
