# Generated by Django 3.2.5 on 2021-08-01 13:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('escape_rooms_app', '0006_alter_game_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='player',
            field=models.ForeignKey(default=98, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='room',
            field=models.ForeignKey(default=98, on_delete=django.db.models.deletion.CASCADE, to='escape_rooms_app.room'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='datetime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='game',
            name='used_jokers_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
