# Generated by Django 3.2.5 on 2021-08-01 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escape_rooms_app', '0007_auto_20210801_1633'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='game',
            constraint=models.UniqueConstraint(fields=('room', 'datetime'), name='game unique room datetime'),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.UniqueConstraint(fields=('room', 'datetime'), name='reservation unique room datetime'),
        ),
    ]
