# Generated by Django 3.2.5 on 2021-08-02 07:30

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('escape_rooms_app', '0008_auto_20210801_2348'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='room',
            constraint=models.CheckConstraint(check=models.Q(('max_players__gte', django.db.models.expressions.F('min_players'))), name='check_room_min_max_players'),
        ),
    ]
