# Generated by Django 3.2.5 on 2021-08-02 09:30

from django.db import migrations, models
import escape_rooms.escape_rooms_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('escape_rooms_app', '0009_room_check_room_min_max_players'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='datetime',
            field=models.DateTimeField(validators=[escape_rooms.escape_rooms_app.validators.validate_start_time]),
        ),
    ]
