# Generated by Django 3.2.5 on 2021-08-02 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escape_rooms_app', '0010_alter_reservation_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='total_rate',
            field=models.FloatField(),
        ),
    ]
